### ISSUE TITLE
Video that shows WALLETH+TREZOR+issuETH in combination

### ISSUE THREAD

**Issue by ligi** [walleth/media#1]
I would have the following in mind:

 - install issuETH ( see http://walleth.org/2017/10/18/issuETH-ethereum-issue-bounties/ for how)
 - add bounty to issue
 - pay testnet ether or tokens to issue from TREZOR account via WALLETH

The most difficult thing will be IMHO the camera-focus on the different screens (TREZOR, mobile, PC) You should see the following scenes:
 - issuETH install
 - add bounty to issue
 - scan QR-Code that was created 
 - transfer Rinkeby ether or better tokens with TREZOR account
 - Interact with TREZOR
 - See the comment from issuETH on the issue that states the transfer

**Comment by ligi** [comment]
Possible extensions: 
 * add the issue-bounty-address as watch-only address on WALLETH on another device and get notified about the transaction on there

**Comment by davalb** [comment]
Hi Ligi, I want to take on this issue. One question though: would it be ok, to split it up into two videos: 
1. walleth + trezor
2. walleth + issueth

The reason being that some people might be interested only in one or the other. People that are interested in both can watch both videos. What do you think?

**Comment by ligi** [comment]
Hey cool - split sounds good to me - I like modules ;-)

**Comment by ligi** [comment]
Already seen #1 - really liked it - so please see @davalb as assigned to this issue (inviting you to the organisation in a minute so I can really assign you) - and it is most likely the bounty will go to @davalb - so please to others do not start working on these videos

**Comment by davalb** [comment]
Hi Ligi, just a short update: The second video is not yet finished, but I am working on it. Problem is the lighting. There are only ~2 hours a day, when the light conditions are good enough. Also the setup of the second video is a bit more complex. I hope to have it finished this week.

**Comment by davalb** [comment]
Just finished the video. Will send it to you in a bit.

**Comment by ligi** [comment]
Cool - just saw the video and like it :+1:
